### ISSUE TITLE
Please add assignment problems.

### ISSUE THREAD

**Issue by akash64259** [raghuramshankar/sensor-fusion-nonlinear-filtering#1]
Hi,
Please add assignment problems statements and which file is the solution of which problem. It would be easier for others for to understand.

Regards,
Akash

**Comment by raghuramshankar** [comment]
Hi Akash, 

You can find the problem statements as images pertaining to each code, with the same name, which have been pushed into each week's subfolder.
For example:

> https://github.com/raghuramshankar/sensor-fusion-nonlinear-filtering/blob/master/01--introduction-and-primer-in-statistics/affineGaussianTransform.png

is the problem statement for:

> https://github.com/raghuramshankar/sensor-fusion-nonlinear-filtering/blob/master/01--introduction-and-primer-in-statistics/affineGaussianTransform.m

I have pushed similar images for all the code. I hope you find them useful.

Best regards,
Raghuram Shankar

**Comment by akash64259** [comment]
Thanks and Regards,
Akash
